### ISSUE TITLE
numpy conflict

### ISSUE THREAD

**Issue by chi86** [cschwan/sage-on-gentoo#334]
Hi,
i just did an update and stumbled upon this dependency conflict:

dev-python/numpy:0

  (dev-python/numpy-1.9.0-r1:0/0::gentoo, ebuild scheduled for merge) conflicts with
    =dev-python/numpy-1.8*[python_targets_python2_7(-),-python_single_target_python2_7(-)] required by (sci-mathematics/sage-6.4-r1:0/0::sage-on-gentoo, installed)
    ^                 ^^^^  

Is there anything i can do to get rig of that?

Thanks in advance!

**Comment by kiwifb** [comment]
Nope. Ok not completely true. It happens because sage depends on numpy 1.8.x and matplotlib 1.3.x. We cannot move sage to numpy 1.9.x without upgrading matplotlib to 1.4.x first (numpy 1.8 can build matplotlib 1.3 and 1.4 but numpy 1.9 won't build matplotlib 1.3). In the main Gentoo tree however they have stabilised numpy 1.9.

There is one thing you can do to make your package manager shut up, put
```
 >=dev-python/numpy-1.9.0
```
 in package.mask

**Comment by chi86** [comment]
Works for me thanks!
