### ISSUE TITLE
Do not block dev-python/gmpy

### ISSUE THREAD

**Issue by devurandom** [cschwan/sage-on-gentoo#339]
Currently `sci-mathematics/sage/sage-6.5.ebuild` contains:
```sh
DEPEND="${CDEPEND}
    !dev-python/gmpy"
```

This causes blockers on my system, as other parts require that package. Please find another way to solve whatever issue gmpy is causing for the build of sage.

**Comment by kiwifb** [comment]
Please understand that this was put there because I had enough explaining people why their system was broken. If you want this fixed properly you need to talk to mpmath/sympy upstream. I already had a word with Fredrik Johansson and he probably just need a bit more pushing.

The problem is not directly in sage. It is in mpmath (I think there may be a bit left in sympy but I believe all the trouble is now in mpmath, but the symptoms are worse in sympy). If you install both gmpy and sage at the same time problem will ensue in mpmath/sympy and ultimately sage when it loads either of them.

mpmath can use either sage or gmpy as backend for arbitrary precision computations. Detection is at runtime and it doesn't behave very well when both are available, unless one or both `MPMATH_NOGMPY` and `MPMATH_NOSAGE` is defined.

So there you have it. For things to work out I have to put in the system `MPMATH_NOGMP` and tell people that they have to switch with `MPMATH_NOSAGE` if they want use gmpy. You really want me to do that?

The solution upstream would be to only use one the backend if a variable is defined.

**Comment by kiwifb** [comment]
Oh yes and the first big symptom is an inability to install sympy.

**Comment by devurandom** [comment]
fredrik-johansson/mpmath#308

**Comment by kiwifb** [comment]
Just out of curiosity what do you need gmpy for? Do you just have it because it is a default dependency?

**Comment by devurandom** [comment]
dev-python/tlslite depends on it by default, and is itself a dependency of some package I use.

**Comment by kiwifb** [comment]
kaa-base? Well it doesn't depend on tlslite[gmp] so you could put
```
dev-python/tlslite -gmp
```
in /etc/portage/package.use and be on your way. That being said I will check if the commit I mentioned in  https://github.com/fredrik-johansson/mpmath/issues/308 solved the horrors that made me make it a blocker. I quoted one message from Vladimir but he came back with the same problem a couple of times...

**Comment by kiwifb** [comment]
It looks safe now so I will lift the restriction for now. But if it gives rise to new issue I will clamp it down again and go back to the drawing board.

**Comment by kiwifb** [comment]
You can play with it now in sage 6.5. Re-open if there is an issue.

**Comment by devurandom** [comment]
Thanks!
