### ISSUE TITLE
cannot import name warn_format_error

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#340]
Starting the notebook I currently read

```
Please wait while the Sage Notebook server starts...
cannot import name warn_format_error
Graphics will not be shown automatically
```

And indeed I cannot see any plots. This is caused by me using `dev-python/ipython-3.0.0` and is related to ipython/ipython@f3d604d86088fcd6aa7b09a691edc0fde26e5573 renaming `warn_format_error` to `catch_format_error` in response to ipython/ipython#7072 triggered by [sage trac ticket 17419](http://trac.sagemath.org/ticket/17419).

I just informed upstream, but I think we might want to deal with this locally. Either by blocking IPython 3 in the notebook ebuild, or (in my opinion preferably) by providing a decorator of that name in case the import fails. Perhaps by copy&pasting the old implementation of that method.

**Comment by gagern** [comment]
[Sage trac ticket 17826](http://trac.sagemath.org/ticket/17826) deals with the upgrade to IPython 3. That ticket apparently simply removes all remaining occurrences of `@warn_format_error`, althouch there are far fewer of these after [17234](http://trac.sagemath.org/ticket/17234) rewrote stuff. I don't think we want to backport 17234 to the 6.5 release. 17826 has some other changes as well, including some completely new files. I'm not sure how much of the remaining stuff is really essential for interop with IPython 3, and how much is optional. Also don't know how much of that is backwards compatible. So I think that unless someone wants to dig deeper into this, blocking IPython 3 is the best solution for now. Although I hate the number of package upgrades which can't proceed due to sage, and hate to be adding one more to that list.

**Comment by kiwifb** [comment]
No I don't want to backport. I must say there are some degrees of annoyance. Here:
 * blocking stable packages because sage is not ready for them. I would consider backporting.
 * blocking unstable packages because the end user is on ~arch. Well that's part of the problems you get for running ~arch.

I don't want to be mean but I prioritize the work on the ground of the end user being on arch with exceptions for which we give a package.keywords file.

In the case of ipython the good news is that it will be in the next beta and 6.6 final. I still need some input on upgrading matplotlib to 1.4.x which is blocking upgrading to numpy 1.9.x.

**Comment by kiwifb** [comment]
I pinned done the `ipython` dependency so in typical use you wouldn't have to mask anything unless there is a conflict with another package.
