### ISSUE TITLE
NTL build error (doesn't find libraries)

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#351]
My build stops at NTL

infos at https://gist.github.com/Alessandro-Barbieri/6a5386259b27ffab282a

```
emerge -pqv '=dev-libs/ntl-6.2.1::sage-on-gentoo'
[ebuild  N    ] dev-libs/ntl-6.2.1  USE="-doc -static-libs {-test}"
```

Seems that he doesn't find crti.o crtibeginS.o crtendS.o crtn.o when compiling ntl.a

**Comment by strogdon** [comment]
Notice that you have `gcc-4.8.4` installed and `ntl` is looking for gcc stuff under `gcc/i686-pc-linux-gnu/4.8.3/`. I suspect you have to rebuild `libtool`, probably due to a gcc upgrade.
```
emerge -1 sys-devel/libtool
```
If that doesn't fix things then there is a very significant problem. I had the same problem here and rebuilding `libtool` fixed it for me.
