### ISSUE TITLE
Up/Downgrade of sage 6.9 <--> 6.10

### ISSUE THREAD

**Issue by juerrose** [cschwan/sage-on-gentoo#389]
For abaut 10 days there is a continous up and downgrade of sage under gentoo:
root@lynx:/usr/local/portage/dev-lang(37)# genlop -t sage | tail -n 27
     Sun Dec 20 11:37:22 2015 >>> sci-mathematics/sage-6.9
       merge time: 17 minutes and 39 seconds.

```
 Sun Dec 27 11:21:42 2015 >>> sci-mathematics/sage-6.10
   merge time: 17 minutes and 44 seconds.

 Sun Dec 27 13:23:41 2015 >>> sci-mathematics/sage-6.10
   merge time: 17 minutes and 9 seconds.

 Mon Dec 28 07:46:18 2015 >>> sci-mathematics/sage-6.9
   merge time: 19 minutes and 44 seconds.

 Mon Dec 28 11:40:11 2015 >>> sci-mathematics/sage-6.10
   merge time: 18 minutes and 14 seconds.

 Mon Dec 28 22:06:56 2015 >>> sci-mathematics/sage-6.9
   merge time: 19 minutes and 45 seconds.

 Mon Dec 28 23:39:38 2015 >>> sci-mathematics/sage-6.10
   merge time: 16 minutes and 45 seconds.

 Wed Dec 30 11:13:18 2015 >>> sci-mathematics/sage-6.9
   merge time: 18 minutes and 43 seconds.

 Fri Jan  1 17:46:52 2016 >>> sci-mathematics/sage-6.10
   merge time: 17 minutes and 36 seconds.
```

see also https://bugs.gentoo.org/show_bug.cgi?id=570300 . I

Is there any idea, how to avoid this.

**Comment by kiwifb** [comment]
I can see where the problem with `sphinx` is coming from but that doesn't explain the loop for `sage` itself. Could you please post `emerge -pvuND world` for when you are presented with a downgrade of `sage`?

**Comment by kiwifb** [comment]
I made a change in 6.10 just now (the dirty way) so you won't have the downgrade of `sphinx` anymore and it should work so long as you stick to `bin-{html,pdf}` useflags.

**Comment by kiwifb** [comment]
What version of `sage-notebook` do you have? I have changed the way that particular dependency is handled in the hot ebuild for the next version of `sage` but I am wondering if you are having trouble because of the presence of a new version that `sage-6.10` is not compatible with in the overlay.

**Comment by juerose** [comment]
I have sage-notebook-0.11.4-r4 since August 12nd 2015.  I not really know what triggers the downgrade to sage-6.9. Now I have sage-6.10 installed, and I can not provoke the downgrade. 

root@lynx:/usr/local/portage/kde-base(32)# qlist -Iv sci-mathematics/sage
sci-mathematics/sage-6.10
sci-mathematics/sage-data-combinatorial_designs-20140630
sci-mathematics/sage-data-conway_polynomials-0.4-r3
sci-mathematics/sage-data-elliptic_curves-0.8
sci-mathematics/sage-data-graphs-20150724
sci-mathematics/sage-data-polytopes_db-20120220
sci-mathematics/sage-notebook-0.11.4-r4


Neither 'emerge -pvuND world',  'emerge -pvt --update --newuse --deep --with-bdeps=y @world',  'revdep-rebuild -p' nor 'emerge -p @preserved-rebuild' want to install sage-5.9:

root@lynx:/usr/local/portage/kde-base(33)# emerge -pvuND world

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  r  U  ] dev-libs/ntl-9.6.2:0/9.6.2::sage-on-gentoo [9.3.0:0/0::gentoo] USE="doc threads%* -static-libs {-test}" 875 KiB
[ebuild  rR    ] dev-libs/ntl-9.3.0::gentoo  USE="doc -static-libs {-test}" 0 KiB
[ebuild  rR    ] sci-libs/linbox-1.3.2-r2::sage-on-gentoo  USE="sage -static-libs" 0 KiB
[ebuild  N     ] sci-mathematics/4ti2-1.6.6::gentoo  USE="-static-libs" 5,508 KiB
[ebuild  rR    ] sci-mathematics/singular-3.1.7_p1-r4::sage-on-gentoo  USE="boost doc emacs examples python readline -flint {-test}" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild     U  ] gnome-extra/gnome-dvb-daemon-0.2.90::gentoo [0.2.10::gentoo] USE="nls vala -totem" 0 KiB
[ebuild  rR    ] sci-mathematics/flint-2.5.2:0/13::sage-on-gentoo  USE="doc ntl -gc -static-libs {-test}" 0 KiB
[ebuild  rR    ] sci-libs/libsingular-3.1.7_p1-r6::sage-on-gentoo  USE="boost flint -debug" 0 KiB
[ebuild  rR    ] sci-mathematics/eclib-20150827:0/2::sage-on-gentoo  USE="boost flint -static-libs" 0 KiB
[ebuild  r  U  ] sci-mathematics/singular-4.0.2::gentoo [3.1.7_p1-r4::sage-on-gentoo] USE="boost doc emacs examples python readline (-flint%) (-test%)" PYTHON_TARGETS="(-python2_7%*)" 17,016 KiB

Total: 10 packages (3 upgrades, 1 new, 6 reinstalls), Size of downloads: 23,399 KiB

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/ntl:0

  (dev-libs/ntl-9.6.2:0/9.6.2::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (dev-libs/ntl-9.3.0:0/0::gentoo, ebuild scheduled for merge) pulled in by
    ~dev-libs/ntl-9.3.0:0/0= required by (sci-mathematics/sage-6.10:0/0::sage-on-gentoo, installed)
    ^             ^^^^^^^^^^                                                                                                                                                 
    (and 1 more with the same problem)

sci-mathematics/singular:0

  (sci-mathematics/singular-4.0.2:0/0::gentoo, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (sci-mathematics/singular-3.1.7_p1-r4:0/0::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    ~sci-mathematics/singular-3.1.7_p1 required by (sci-mathematics/sage-6.10:0/0::sage-on-gentoo, installed)
    ^                         ^^^^^^^^ 
...

root@lynx:/usr/local/portage/kde-base(34)# emerge -pvt --update --newuse --deep --with-bdeps=y @world

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  r  U  ] sci-mathematics/singular-4.0.2::gentoo [3.1.7_p1-r4::sage-on-gentoo] USE="boost doc emacs examples python readline (-flint%) (-test%)" PYTHON_TARGETS="(-python2_7%*)" 17,016 KiB
[ebuild     U  ] gnome-extra/gnome-dvb-daemon-0.2.90::gentoo [0.2.10::gentoo] USE="nls vala -totem" 0 KiB
[ebuild  rR    ] sci-mathematics/eclib-20150827:0/2::sage-on-gentoo  USE="boost flint -static-libs" 0 KiB
[ebuild  rR    ] sci-mathematics/singular-3.1.7_p1-r4::sage-on-gentoo  USE="boost doc emacs examples python readline -flint {-test}" PYTHON_TARGETS="python2_7" 0 KiB
[nomerge       ] sci-mathematics/singular-4.0.2::gentoo [3.1.7_p1-r4::sage-on-gentoo] USE="boost doc emacs examples python readline (-flint%) (-test%)" PYTHON_TARGETS="(-python2_7%*)" 
[ebuild  N     ]  sci-mathematics/4ti2-1.6.6::gentoo  USE="-static-libs" 5,508 KiB
[ebuild  rR    ] sci-libs/linbox-1.3.2-r2::sage-on-gentoo  USE="sage -static-libs" 0 KiB
[ebuild  rR    ] sci-libs/libsingular-3.1.7_p1-r6::sage-on-gentoo  USE="boost flint -debug" 0 KiB
[ebuild  rR    ]  sci-mathematics/flint-2.5.2:0/13::sage-on-gentoo  USE="doc ntl -gc -static-libs {-test}" 0 KiB
[ebuild  rR    ] dev-libs/ntl-9.3.0::gentoo  USE="doc -static-libs {-test}" 0 KiB
[ebuild  r  U  ] dev-libs/ntl-9.6.2:0/9.6.2::sage-on-gentoo [9.3.0:0/0::gentoo] USE="doc threads%* -static-libs {-test}" 875 KiB

Total: 10 packages (3 upgrades, 1 new, 6 reinstalls), Size of downloads: 23,399 KiB

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/ntl:0

  (dev-libs/ntl-9.6.2:0/9.6.2::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (dev-libs/ntl-9.3.0:0/0::gentoo, ebuild scheduled for merge) pulled in by
    ~dev-libs/ntl-9.3.0:0/0= required by (sci-mathematics/sage-6.10:0/0::sage-on-gentoo, installed)
    ^             ^^^^^^^^^^                                                                                                                                                 
    (and 1 more with the same problem)

sci-mathematics/singular:0

  (sci-mathematics/singular-4.0.2:0/0::gentoo, ebuild scheduled for merge) pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (sci-mathematics/singular-3.1.7_p1-r4:0/0::sage-on-gentoo, ebuild scheduled for merge) pulled in by
    ~sci-mathematics/singular-3.1.7_p1 required by (sci-mathematics/sage-6.10:0/0::sage-on-gentoo, installed)

root@lynx:/usr/local/portage/kde-base(35)# revdep-rebuild -p 
 * This is the new python coded version
 * Please report any bugs found using it.
 * The original revdep-rebuild script is installed as revdep-rebuild.sh
 * Please files bugs at: https://bugs.gentoo.org/
 * Collecting system binaries and libraries
 * Checking dynamic linking consistency
 * Assign files to packages

emerge  --pretend --oneshot --complete-graph=y sci-chemistry/modeller:0

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] sci-chemistry/modeller-9.12-r3 

root@lynx:/usr/local/portage/kde-base(36)# emerge -p @preserved-rebuild

These are the packages that would be merged, in order:

Calculating dependencies... done!
root@lynx:/usr/local/portage/kde-base(37)#

**Comment by kiwifb** [comment]
Cannot do much more without seeing a downgrade in action. That being said, I will think about what could cause it.
