### ISSUE TITLE
Packages contained in gentoo and sage-on-gentoo

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#391]
I'd like some clarification on what to do about packages which are contained *with the same version* in both the main `gentoo` tree and the `sage-on-gentoo` overlay. In those cases, repository priorities will decide which one to use. I think the default setting when using layman is to use priority 50 for  overlays by default, and priority 100 for the standard repository. So the standard `gentoo` overlays take precedence. This bit me today, since due to #380 I need to use the `sympy` ebuild from the `sage-on-gentoo` overlay. On the other hand, often Sage bumps some ebuild locally before it makes it into the main portage tree. For those cases, I tend to prefer the main `gentoo` version since it's newer when it gets included, and likely has seen more useful work applied to it, particularly if it derived from the Sage version.

So what's the official stance here? Should people install `sage-on-gentoo` with a priority higher than 100? If so, the [README](https://github.com/cschwan/sage-on-gentoo/blob/master/README.rst) should say so. Or is it supported to have `sage-on-gentoo` at a lower priority than `gentoo`? In that case, I think there should be a way to override that on a per-package basis. Like e.g. a masks file which people can symlink into `/etc/portage/package.mask/` which masks the `::gentoo` version of a package. Either just for a specific version, or for the whole package if it is to be assumed that the incompatibility with Sage will affect all versions.

Currently, I see these packages affected:

```
dev-python/cvxopt/cvxopt-1.1.8.ebuild
dev-python/numpy/numpy-1.10.2-r2.ebuild
dev-python/numpy/numpy-1.10.4.ebuild
dev-python/sphinx/sphinx-1.2.2.ebuild
dev-python/sphinx/sphinx-1.2.3.ebuild
dev-python/sympy/sympy-0.7.6.1-r1.ebuild
media-gfx/tachyon/tachyon-0.98.9-r2.ebuild
sci-mathematics/gmp-ecm/gmp-ecm-6.4.4-r1.ebuild
```

Note that all of this is for unstable `~ARCH` keyword, so any solution based on selective keywording won't apply here.

**Comment by kiwifb** [comment]
That's a bit strange. My assumption, which has been the default for a long time is that overlays have precedence over the main tree. If that behavior is changing I will have to adapt accordingly.

- `cvxopt-1.1.8` bumped here first and then the main tree didn't use my ebuild. Both are OK to use. I am just being an ass keeping that one around because my changes were overlooked.
- `numpy` version in s-o-g has a patch pending upstream that is essential, if someone helps me write the tests it will be included.
- `sphinx` only needed if you want to build the documentation. Has a couple of patch without which it doesn't happen. People using "stable" `sage`(i.e. not -9999) and bin-{html,pdf} do not need this.
- `sympy` the person bumping the main tree version decided to remove the `system-mpmath` useflag and to not remove `mpmath` from `sympy`. It is so vital that it be removed that I remove `mpmath` without the useflag. Sage upstream now removes it as well otherwise sage is borked. And even more interesting, upstream `sympy` has removed it and it won't be included in the next version of `sympy`, it will be a dependency instead.
- `tachyon` s-o-g overlay has proper support for a macos prefix, not useful if you are not on a mac. There may be a bug open for it somewhere.
- `gmp-ecm` I actually cover case where the in tree ebuild fails for older hardware, the `r2` has more support for macos on prefix as well.

If the new behavior is that the main tree takes precedence I will have to bump versions.

**Comment by gagern** [comment]
The `layman` man page writes this:

> `-p LEVEL, --priority=LEVEL`
> Use this option in combination with the --add.
>
> * `make.conf`:: It will modify the priority of the added overlay and thus influence the order of entries in the `make.conf` file. The lower the priority, the earlier in the list the entry will be mentioned in the make.conf.
> * `repos.conf`:: It will modify the priority in the `repos.conf` file, and thus influence the portage overlay priority. Read `man portage` for more details on overlay priority. Use a value between 0 and 100. The default value is 50.

The `portage` man page says

> repos with higher priorities are preferred when ebuilds with equal versions are found in multiple repos (see the `emerge --info --verbose` repo display for a listing of repos and their corresponding priorities).

I could not find out where my `/etc/portage/repos.conf/gentoo.conf` originated. And it took me some searching till I found https://wiki.gentoo.org/wiki/Overlay#Priorities writing

> The default Gentoo Portage tree will have a priority of -1000. That means that all other overlays generally take precedence as they are assigned a higher priority. That is the default behavior, because overlays are designed to "lay over/on top" of the portage tree.

So either I manually tinkered with my `gentoo` priority, or I got that file generated at a point in time when the default was something different. So probably this is mostly my problem, but the listing you provided helps a lot.
