### ISSUE TITLE
Overlay complains missing repo

### ISSUE THREAD

**Issue by hungshihhan** [cschwan/sage-on-gentoo#403]
After including the overlay `sage-on-gentoo` by executing `layman -a sage-on-gentoo`, emerge keeps complaining with the following message:
`Unavailable repository 'science' referenced by masters entry in '/var/lib/layman/sage-on-gentoo/metadata/layout.conf`
Is there any way to remove the warning?

**Comment by kiwifb** [comment]
I made the `sage-on-gentoo` overlay depend on the `science` overlay because at the time `ipython-4` was only available there. While a number of things have migrated in the main tree, some stuff is still present in the `science` overlay. So my recommendation to you is to install the science overlay first
```
layman -a science
```

**Comment by kiwifb** [comment]
I have updated the instructions to make that extra step clear.
