### ISSUE TITLE
Conflicting initial use flags

### ISSUE THREAD

**Issue by rhopfer** [cschwan/sage-on-gentoo#443]
The ebuild selected to satisfy "sage" has unmet requirements.
- sci-mathematics/sage-7.4-r2::sage-on-gentoo USE="X bin-html pdf -bin-pdf -bliss -debug -html -latex -libbraiding -libhomfly -modular_decomposition -sagenb -testsuite" L10N="de en -ca -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    pdf? ( sagenb ) bin-html? ( !pdf )

**Comment by kiwifb** [comment]
`bin-html` is incompatible with `html` and `pdf` cannot be selected at the same time. There is a special package.use file for binary documentation in the overlay `package.use/99sage-bin-doc` that you can use to set sane flags for the sage documentation. If you want to have `pdf` doc you might want to add `bin-pdf` to your useflags for sage.

It is set up that way because:
* it takes some time to build the doc, even with several threads, there is a bottle neck - then at install all the png files are inspected and corrected. The later takes a long time without giving any kind of progress indicator.
* pdf is sometimes tricky to produce
* In the not so distant past you needed to have specific version of `sphinx` that may be different (lower) than the one you had installed which was a burden. This is not the case anymore.

Some people still want to build the doc themselves, that's what the plain `html` and `pdf` useflags are for. People using sage-9999 have no choice but to build the doc.

**Comment by rhopfer** [comment]
Sorry for my late response. It is not good to have conflicting initial use flags by default. It is common on gentoo to set the doc use flag only if you really want it for a package, so I think it is better to disable the  use flags pdf and bin-html by default.

**Comment by kiwifb** [comment]
Yes, at some point I was calling it `pdf-doc` or `docpdf`. I will review the options. Most regular users of sage are expecting the doc to be present which is why I have that default, and the html doc is expected when running the testsuite - which unfortunately has still to be run after installation. Note that I already do some trimming - I try respecting `l10n` as much as possible rather shipping all the available languages for example.

**Comment by kiwifb** [comment]
OK `bin-html` is not the default anymore.

**Comment by kiwifb** [comment]
OK I changed all useflags so they are quite specific now and shouldn't clash with flags in common use, sometimes for widely different things. We now have `doc-{htm,pdf}{,-bin}`, `doc-html-bin` is default again for now but it shouldn't conflict with plain `html` which may be abused for many things.
