### ISSUE TITLE
patch gift

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#469]
A patch for building polymake-3.0_p2[singular]
maybe the path needs changes in base on how the patch is applied

```
--- work/bundled/singular/configure.pl  2016-07-22 14:23:31.000000000 +0200
+++ /tmp/configure.pl   2017-05-13 07:13:33.025861902 +0200
@@ -46,7 +46,7 @@
    chomp $singular_prefix;
    # yes we need it twice ...

-   $Libs = join(" ",$LDflags =~ m/(-l\w+)/g) . " -lfactory -lresources -lpolys -lomalloc";
+   $Libs = join(" ",$LDflags =~ m/(-l\w+)/g) . " -lfactory -lsingular_resources -lpolys -lomalloc";
    $LDflags =~ s/ -l\w+//g;
    $LDflags =~ s/-L(\S+)/-L$1 -Wl,-rpath,$1/g;
    my $libdir = $1;
```

**Comment by Alessandro-Barbieri** [comment]
my bad, wrong repository

**Comment by kiwifb** [comment]
Actually, I have thought many times to do something about `polymake`. But the complexity of the possible circular dependencies between `singular` and `polymake` have always put me off.

Anyway, I disagree with the "letter" of your patch (as opposed to its "spirit"). `singular-4` installs a .pc file, make use of it rather than hard code libraries. `pkg-config --libs-only-l Singular`'s output is really what you want to use.

**Comment by Alessandro-Barbieri** [comment]
I searched only for the failure and fixed it: something like cannot find -lresources

**Comment by kiwifb** [comment]
That's ok, but using `pkg-config` is future proofing you, so long as `singular` upstream maintains it properly.
