### ISSUE TITLE
arb-2.17.0 is in ::gentoo

### ISSUE THREAD

**Issue by orlitzky** [cschwan/sage-on-gentoo#571]
Just a heads up, I added the new version to the ::gentoo tree so the overlay copy is redundant now. In the future just let me know when you have an ebuild for a new version (or open a PR) and I'll commit it.

**Comment by kiwifb** [comment]
Thanks closing with b54b5995d18e152452313a898ae77d7a2d516f7c

**Comment by orlitzky** [comment]
In case you miss the bugzilla emails, I did the same thing today with gmp-ecm and flint. Patrick (patrick@gentoo.org) doesn't really care if you commit fixes for packages that he maintains, and I've started to take advantage of that fact.

**Comment by kiwifb** [comment]
I am copied on all science stuff in bugzilla. I am fairly sure I sent an email to patrick a while ago about gmp-ecm and I am still waiting for an answer.
Note on `RESTRICT=mirror` I usually avoid those now but back 10 years ago we were putting those so that sources wouldn't be fetched from gentoo mirror were they would invariably be missing. That makes downloading sources faster since you don't have to wait for your configured mirror(s) to reject your request.

There are a few details to fix but I think we should do something about suitesparse ebuilds next. There is a handful of bugs in bugzilla that will go away once we port. https://github.com/cschwan/sage-on-gentoo/blob/master/package.keywords/SuiteSparse-5.4.0 note that there is now a 5.7.1 at least and upstream makes me mad
```
* CXSparse 3.2.0: version was incorrect in CXSparse/Include/cs.h;
    the corresponding CSparse v3.2.0 had the correct version information
    in its cs.h include file.
```
change of code without bumping the version :angry:

**Comment by orlitzky** [comment]
> There are a few details to fix but I think we should do something about suitesparse ebuilds next.

I just pushed updates for all of these. I'll wait a few days and then start to prune the old, buggy versions and close all the bugs.

**Comment by kiwifb** [comment]
Bear in mind that even if we go to 5.7.1 most of those versions won't change because they are decoupled. I am using https://github.com/kiwifb/suitesparse which I forked from the original work from bicatali when he was doing it. The current packaging of `suitesparse_config` is wrong and I have to fix it.

**Comment by kiwifb** [comment]
Correction, they are all wrong probably.

**Comment by kiwifb** [comment]
I pushed some changes to https://github.com/kiwifb/suitesparse. I get package versions differently now. For all packages except `suitesparse_config` there is no change. For `suitesparse_config` I inherited a scheme where it always had the same version as the meta-package (even if it didn't change between versions). I know use the proper version from upstream - which sometimes match.

I adopted the sonames from upstream. There is no revisions or age defined unfortunately. We can only hope upstream knows what a soname stands for in terms of compatibility. Hopefully, that means we can depend on slot/sublot version of libraries without having breakages. This is a first draft in that it works but definitely needs refinements. I just found a way to blanket all the packages very quickly.

**Comment by kiwifb** [comment]
Of course upstream had to mess up their own scheme. Version number of `klu` is different between the changelog and the makefile. Changelog is the correct value in this case. Overall in 5.7.1 we only have a new version of `suitesparse_config` (trivial changes mostly) and `cholmod`. There are two other packages distributed with suitesparse that have had changes. But those can be found separately and have cmake build systems.
