### ISSUE TITLE
gap-core remove recommended_pkgs useflag

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#631]
gap-core is causing alot of trouble when updating.
Also ebuild shouldn't have useflags for runtime optional packages so if those packages are necessary to run sage, add them as a dependency there.

See https://projects.gentoo.org/qa/policy-guide/dependencies.html#pg0001

**Comment by kiwifb** [comment]
Hi Alessandro, 

Sorry for taking so long to provide you with some answers. I am aware that gap-core is giving difficulties for upgrading. I haven't been able to provide any kind of smooth upgrade path between major revision of gap since at least gap-4.10. I have been trying to get some way to handle gap package dependencies and sources in somewhat consistent ways and failing with one issue or another each time. I am hoping that 4.11.0 forward will be better.

For the recommended packages, yes I could and probably should handle it some other way. They are expected by sage as part of a minimal gap install. The list does not come from sage but from gap upstream itself as the minimum recommended set if my memory serves me right. I could handle it as a meta package which I would hope would be OK with you. My issue with meta package is that the last time I tried to provide one for sage (before gap 4.9) I ended up abandoning it. So far updating the list in the gap ebuild itself has been a better assurance that it would be maintained.

**Comment by Alessandro-Barbieri** [comment]
I've reworded the first message because it was too broken.
The usual policy for runtime optional packages is to not depend on them and instead send a message to the user with optfeature.
Also I'm not getting the point of the meta package maintenance: what's the burden with it?

**Comment by Alessandro-Barbieri** [comment]
I'm trying to make some changes locally but I've hit another issue

**Comment by kiwifb** [comment]
The kill all problems procedure for upgrading is probably still https://github.com/cschwan/sage-on-gentoo/blob/master/metadata/news/2019-04-08-gap-upgrade/2019-04-08-gap-upgrade.en.txt 

The maintenance problem is always I am a lone maintainer. But if I have the motivation because of policy I probably can do that :)

**Comment by fingolfin** [comment]
Is this still an issue? At least `recommended_pkgs` seems to be gone.

(Apologies if this is a dumb question; I know very little about Gentoo)

**Comment by kiwifb** [comment]
Yes I removed quite a bit of stuff at gap 4.12 and this is certainly obsolete. Although, Alessandro may have new complaints since then :)
