### ISSUE TITLE
giac-1.7.0.13-r1 fails install phase on Prefix

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#663]
```
rm: cannot remove '/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/giac-1.7.0.13-r1/image/storage/strogdon/gentoo-rap/usr/share/doc/giac-1.7.0.13-r1/doc/Exemples': No such file or directory
 * ERROR: sci-mathematics/giac-1.7.0.13-r1::gentoo failed (install phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 127:  Called src_install
 *   environment, line 2108:  Called die
 * The specific snippet of code:
 *       rm -r "${ED}/usr/share/doc/${PF}/doc/Exemples" || die;
```
It looks like a double prefix of sorts. The `Exemples` folder is located under
```
/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/giac-1.7.0.13-r1/image/usr/share/giac/doc/
```
And under my prefix's image folder there is
```
ls /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/giac-1.7.0.13-r1/image
storage  usr
```

**Comment by strogdon** [comment]
Just realized `giac-1.7.0.13-r1` is a portage, not s-o-g, package.

**Comment by strogdon** [comment]
See https://bugs.gentoo.org/829385

**Comment by strogdon** [comment]
Not a solution to the Prefix issue but do you have on Gentoo under `/usr/share`
```
/usr/share/giac
/usr/share/giac.backup.0000
```
Here `/usr/share/giac` is empty and `/usr/share/giac.backup.0000` is a symlink to `/usr/share/doc/giac-1.7.0.13-r1`. I'm guessing that `/usr/share/giac` was a holdover from a previous install. Removing `/usr/share/giac`, the `backup` symlink and reinstalling `giac` seems to look better - `/usr/share/giac` is now a symlink to `/usr/share/doc/giac-1.7.0.13-r1`.

**Comment by kiwifb** [comment]
I actually do have `/usr/share/giac.backup.0000` and it is a dead link to `doc/giac-1.7.0.13-r1`.  I have 1.7.0-43 currently installed and I don't remember if I imported all the changes of the main tree regarding the doc. There is an issue that some of the manual is under a non-free license and shouldn't be redistributed the way we do. The other issue is that by default the doc is not installed in the right spot according to Gentoo policies. The link is because it is difficult to patch the right location inside giac, so a pointer was left.

**Comment by strogdon** [comment]
I think so. I have proposed a fix at https://bugs.gentoo.org/829385 on Prefix that now behaves like Gentoo, i.e.

`EPREFIX/usr/share/giac` is a symlink to `EPREFIX/usr/share/doc/giac-1.7.0.13-r1` where the compressed docs are installed.

**Comment by strogdon** [comment]
I'll close this. Fixed with https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=ecc4a10ede9f57abd1770d5c6ac20184ec317fa6
