### ISSUE TITLE
Can't sync the sage-on-gentoo overlay using git

### ISSUE THREAD

**Issue by DrBanana419** [cschwan/sage-on-gentoo#670]
Hi I use git to sync portage. Whenever I use `emerge --sync`, all the other overlays I have sync without issues, except this one. Here is the error:
```
>>> Syncing repository 'sage-on-gentoo' into '/var/db/repos/sage-on-gentoo'...
/usr/bin/git fetch origin
Updating 9954f58a..09ee3548
error: Your local changes to the following files would be overwritten by merge:
	package.keywords/sage-9.4
Please commit your changes or stash them before you merge.
Aborting
!!! git merge error in /var/db/repos/sage-on-gentoo
```
In my `/etc/portage` I have a `package.keywords` directory specifically for this overlay, and a `package.accept-keywords` directory for my personal stuff (since I know the former is deprecated). I've been facing this issue for months now.

**Comment by kiwifb** [comment]
That kind of message happens when you directly modified a file in the overlay. If you go to `/var/db/repos/sage-on-gentoo' and run `git status` it should tell you you have modified that particular file.

A solution to this is to run the following command from the `/var/db/repos/sage-on-gentoo' folder
```
git checkout package.keywords/sage-9.4
```
Note that you don't a `/etc/portage/package.keywords` for this overlay. But you made me look and I see the README is actually incorrect in telling you to have one.

**Comment by kiwifb** [comment]
The README is now updated, It doesn't mention `/etc/portage/package.keywords` anymore.
