### ISSUE TITLE
dev-gap/transgrp fetch fail

### ISSUE THREAD

**Issue by 2403772980ygy** [cschwan/sage-on-gentoo#679]
It utters the following error:
```
>>> Downloading 'https://www.math.colostate.edu/~hulpke/transgrp/transgrp3.3.tar.gz'
--2022-02-13 12:35:54--  https://www.math.colostate.edu/~hulpke/transgrp/transgrp3.3.tar.gz
Resolving www.math.colostate.edu... 129.82.154.79
Connecting to www.math.colostate.edu|129.82.154.79|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.math.colostate.edu/ED/notfound.html [following]
--2022-02-13 12:35:55--  http://www.math.colostate.edu/ED/notfound.html
Connecting to www.math.colostate.edu|129.82.154.79|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.math.colostate.edu/ED/notfound.html [following]
--2022-02-13 12:35:56--  https://www.math.colostate.edu/ED/notfound.html
Connecting to www.math.colostate.edu|129.82.154.79|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 274 [text/html]
Saving to: ‘/var/cache/distfiles/transgrp3.3.tar.gz.__download__’

/var/cache/distfile 100%[===================>]     274  --.-KB/s    in 0s      

2022-02-13 12:35:58 (111 MB/s) - ‘/var/cache/distfiles/transgrp3.3.tar.gz.__download__’ saved [274/274]

!!! Fetched file: transgrp3.3.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      274
!!! Expected: 61293979
Refetching... File renamed to '/var/cache/distfiles/transgrp3.3.tar.gz._checksum_failure_.srbbr8i7'

!!! Couldn't download 'transgrp3.3.tar.gz'. Aborting.
 * Fetch failed for 'dev-gap/transgrp-3.3', Log file:
 *  '/var/tmp/portage/dev-gap/transgrp-3.3/temp/build.log'
```

**Comment by kiwifb** [comment]
version 3.0 should still be available and suitable by the way.

**Comment by kiwifb** [comment]
Scratch that, it is not available at that page anymore either. Upstream doesn't keep older copies anymore. Which means the page from the gap website itself is pointing to nothing.

**Comment by kiwifb** [comment]
OK fixed by 92409ab644fc4c1eb9eec6263ddc4d68ff614d8b but I am keeping this open while I work with something more durable for sources. I will probably have to fetch commits from github.

**Comment by hulpke** [comment]
What happened is that I updated the package on Friday (to version 3.5, now allowing for degree 48), and on this occasion deleted the old versions that had accumulated and filled up the disk space.

Since the `PackageInfo.g` file points to this new version now, that should not have caused any issues for GAP's fetching of package archives -- How was I to know that others are fetching separately (I suggest you let people know if you rely on their web pages for regular fetch).

I will see tomorrow, once I'm back in the office whether I can rescue the old archive from a backup and if so will restore it.

(If you decide to rather go through the github repository, which probably is not worth your time, be aware that you will have to go in the `doc` folder, call `sh ./makedoc` to produce the manual. The main folder `makepackage` is the wrapping script.)

**Comment by kiwifb** [comment]
I have copies of version 3.0 and 3.3 on my hard drive if you need those precise version to be restored I can mirror them. Thanks for warning me about `makedoc` - I am not sure I have the right stuff in place for it to work.

**Comment by hulpke** [comment]
Thank you. I have now restored the archive of transgrp3.3 to the web pages.

My intention is not to keeop such archives in perpetuity, but if you let me know your needs on older releases I am happy to accommodate them.

**Comment by kiwifb** [comment]
@hulpke I didn't realise you are upstream. It indeed doesn't make sense for you to keep those things in perpetuity especially if they are included in the next version. In an ideal world there would be a repository which can kept old versions forever but those things are at least at the level of national institutions.

My needs are just to know when you are releasing stuff so I can keep up to date. Possibly have an older version if there is a compatibility break in gap, then a version working with the old gap probably should be kept around longer.
